<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'matic',
	'db_user' => 'root',
	'db_password' => 'smallworld',
	'db_server_version' => '5.5.5-10.0.29-MariaDB-0ubuntu0.16.04.1',
	'mailer_from_name' => 'nitin antony',
	'mailer_from_email' => 'nitin@smallworld.io',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'root',
	'mailer_password' => 'smallworld',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '65e91c7ad2e123aa0d65e8248f05926dd500901203c8614b000de1e8d18b21f7',
	'site_url' => 'http://127.0.0.1/mautic/index.php',
);
